version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore Api/Api.csproj
  build:
    commands:
      - dotnet build Api/Api.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ Api/Api.csproj
artifacts:
  files:
    - '**/*'