version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
        - db
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__PgAdminConnection=User ID=pgsadmin;Password=admin123;Host=localhost;Port=5455;Database=downtown-db;Pooling=true;
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  db:
    image: postgres:latest
    restart: always
    environment:
        - POSTGRES_USER=pgsadmin
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_DB=downtown-db
    ports:
        - '5456:5432'
    volumes:
        - db:/var/lib/postgresql/data
    hostname: localhost

volumes:
  db:
    driver: local